name: Docker Build and Push

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天运行
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest n8n version
        id: n8n_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/n8n-io/n8n/releases/latest | jq -r .tag_name | sed 's/n8n@//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            N8N_VERSION=${{ steps.n8n_version.outputs.version }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/n8ncn:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/n8ncn:${{ steps.n8n_version.outputs.version }}